version: '3.8'
services:
  user_db:
    image: mysql:8.0
    container_name: mam_user_db
    restart: always
    env_file:
      - ./user-service/.env
    ports:
      - "3306:3306"
    volumes:
      - user_db_data:/var/lib/mysql

  product_db:
    image: mysql:8.0
    container_name: mam_product_db
    restart: always
    env_file:
      - ./product-service/.env
    ports:
      - "3307:3306"
    volumes:
      - product_db_data:/var/lib/mysql 
volumes:
  user_db_data:
  product_db_data: